---
- hosts: all
  tasks:
    - name: Clone peace watcher project
        git:
            repo: "https://github.com/lcshlr/data-engineering-sentiment-analysis"
            dest: "{{ ansible_env.HOME }}/data-engineering-sentiment-analysis"
    
    - name: Setup API IP 
      lineinfile: 
       dest: {{ ansible_env.HOME }}/data-engineering-sentiment-analysis/public/config.js
       regexp:  'window.appConfig'
       line:  "window.appConfig = {'API_URL' : 'http://{{ public_ip }}:5000'}"
    
    - name: Stop all services
      become: yes
      docker_compose:
        project_src: /home/ubuntu/docker/data-engineering-sentiment-analysis
        build: no
        stopped: yes
    
    - name: Launch Docker
      become: yes
      docker_compose:
        project_src: /home/ubuntu/docker/data-engineering-sentiment-analysis
        files: docker-compose.yml
        build: yes

     
