---
- hosts: all
  tasks:
    - name: Setup API IP 
      lineinfile: 
       dest: /home/ubuntu/docker/data-engineering-sentiment-analysis/public/config.js
       regexp:  'window.appConfig'
       line:  "window.appConfig = {'API_URL' : 'http://13.37.71.135:5000'}"
    
    - name: Stop all services
      become: yes
      docker_compose:
        project_src: /home/ubuntu/docker/data-engineering-sentiment-analysis
        build: no
        stopped: yes
    
    - name: Launch Docker
      become: yes
      docker_compose:
        project_src: /home/ubuntu/docker/data-engineering-sentiment-analysis
        files: docker-compose.yml
        build: yes

     
